semi = false
tabWidth = 2
singleQuote = true
printWidth = 100
trailingComma = "none"

plugins = ["prettier-plugin-organize-attributes", "prettier-plugin-css-order", "prettier-plugin-organize-imports"]

attributeSort = "ASC"