# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
environment: development
# whoogle_base_url: http://127.0.0.1:5000
# languagetool_base_url: http://127.0.0.1:8010
