/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Search for products.
         */
        post: operations["search_search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SearchParams */
        SearchParams: {
            /** Query */
            query: string;
            /** Region */
            region: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Name */
            name: string;
            /** Characteristics */
            characteristics?: {
                [key: string]: string;
            };
            /** Price */
            price: string | null;
            /** Image Link */
            image_link: string | null;
        };
        /** SearchResults */
        SearchResults: {
            original_params: components["schemas"]["SearchParams"];
            /** Sources */
            sources: components["schemas"]["SearchSource"][];
        };
        /** SearchSource */
        SearchSource: {
            /**
             * Source Type
             * @enum {string}
             */
            source_type: SearchSourceSource_type;
            /** Source Url */
            source_url: string;
            /** Source Title */
            source_title: string;
            /** Source Favicon Url */
            source_favicon_url: string | null;
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaSearchParams = components['schemas']['SearchParams'];
export type SchemaSearchResult = components['schemas']['SearchResult'];
export type SchemaSearchResults = components['schemas']['SearchResults'];
export type SchemaSearchSource = components['schemas']['SearchSource'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    search_search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchParams"];
            };
        };
        responses: {
            /** @description Found products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
export enum SearchSourceSource_type {
    yandex_market = "yandex_market",
    wildberries = "wildberries",
    ozon = "ozon",
    runet = "runet"
}
