/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Action */
        post: operations["post_action_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Actions */
        get: operations["get_all_actions_actions_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contracts */
        get: operations["list_contracts_contracts_get"];
        put?: never;
        /** Create Contract */
        post: operations["create_contract_contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/by-inn/{inn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contracts By Inn */
        get: operations["get_contracts_by_inn_contracts_by_inn__inn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/by-sku/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contracts By Sku Id */
        get: operations["get_contracts_by_sku_id_contracts_by_sku__sku_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_contracts__contract_id__get"];
        put?: never;
        post?: never;
        /** Delete Contract */
        delete: operations["delete_contract_contracts__contract_id__delete"];
        options?: never;
        head?: never;
        /** Update Contract */
        patch: operations["update_contract_contracts__contract_id__patch"];
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current user info (session creates user with random UUID if needed).
         *     Includes organization name and distinct OKVED codes from contracts when `inn_number` is set.
         */
        get: operations["get_me_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/search-inn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Inn
         * @description Search organizations by INN prefix (if `query` is digits) or by name substring (case-insensitive).
         *     Returns INN, organization name, and OKVED codes.
         */
        get: operations["search_inn_user_search_inn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/set-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Set Info
         * @description Set user inn number in session.
         *     Response includes organization name and OKVED codes from the contracts dataset when `inn_number` is set.
         */
        get: operations["set_info_user_set_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout (clear session)
         */
        post: operations["logout_user_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Each browser session maps to a MongoDB user row (`uid` in cookie). Filter by `inn_number` to see who picked which INN.
         */
        get: operations["list_sessions_user_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_user_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/sessions/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_user_sessions__user_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_user_sessions__user_id__delete"];
        options?: never;
        head?: never;
        /** Patch Session */
        patch: operations["patch_session_user_sessions__user_id__patch"];
        trace?: never;
    };
    "/images/thumbnail/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thumbnail Route
         * @description Redirect to thumbnail URL for a SKU id.
         *     Returns 404 if thumbnail is not found.
         */
        get: operations["get_thumbnail_route_images_thumbnail__sku_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/sku/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Random Skus */
        get: operations["get_random_skus_dataset_sku_random_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/contract/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Random Contracts */
        get: operations["get_random_contracts_dataset_contract_random_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/contract/by-inn/{inn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contracts By Inn */
        get: operations["get_contracts_by_inn_dataset_contract_by_inn__inn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/contract/by-sku/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contracts By Sku Id */
        get: operations["get_contracts_by_sku_id_dataset_contract_by_sku__sku_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/sku/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sku */
        get: operations["get_sku_dataset_sku__sku_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/sku/bulk-by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Skus By Ids */
        post: operations["post_skus_by_ids_dataset_sku_bulk_by_ids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/contract/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_dataset_contract__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/train-personalization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Personalization */
        post: operations["train_personalization_search_train_personalization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear */
        post: operations["clear_search_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index */
        post: operations["index_search_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/refresh-analyzers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Analyzers */
        post: operations["refresh_analyzers_search_refresh_analyzers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: ActionType;
        /** CartAddActionCreate */
        CartAddActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: CartAddActionCreateType;
            data: components["schemas"]["SkuIdActionData"];
        };
        /** CartRemoveActionCreate */
        CartRemoveActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: CartRemoveActionCreateType;
            data: components["schemas"]["SkuIdActionData"];
        };
        CharacteristicValue: string | number;
        /** Contract */
        Contract: {
            /** Name */
            name: string;
            /** Contract Id */
            contract_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Cost */
            cost: number;
            /** Customer Inn */
            customer_inn: number;
            /** Customer Name */
            customer_name: string;
            /** Customer Region */
            customer_region: string;
            /** Supplier Inn */
            supplier_inn: number;
            /** Supplier Name */
            supplier_name: string;
            /** Supplier Region */
            supplier_region: string;
            /** Okveds */
            okveds?: string[];
            /** Sku Ids */
            sku_ids: number[];
        };
        /** ContractCreate */
        ContractCreate: {
            /** Name */
            name: string;
            /** Sku Ids */
            sku_ids: number[];
        };
        /** ContractListResponse */
        ContractListResponse: {
            /** Items */
            items: components["schemas"]["Contract"][];
            /** Total */
            total: number;
        };
        /** ContractUpdate */
        ContractUpdate: {
            /** Name */
            name?: string | null;
            /** Sku Ids */
            sku_ids?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InnSearchResult */
        InnSearchResult: {
            /** Inn */
            inn: number;
            /** Name */
            name: string;
            /**
             * Okveds
             * @default []
             */
            okveds: string[];
            /**
             * Contracts Count
             * @default 0
             */
            contracts_count: number;
        };
        /**
         * PersonalizationRankDelta
         * @description Compared to retrieval order before personalization; only SKUs present in the final page.
         */
        PersonalizationRankDelta: {
            /** Upranked */
            upranked: components["schemas"]["PersonalizationRankMove"][];
            /** Downranked */
            downranked: components["schemas"]["PersonalizationRankMove"][];
        };
        /**
         * PersonalizationRankMove
         * @description Single SKU whose position changed after LightFM rerank (0-based indices).
         */
        PersonalizationRankMove: {
            /** Sku Id */
            sku_id: number;
            /**
             * From Index
             * @description Position in the pre-rerank candidate list (full retrieve window)
             */
            from_index: number;
            /**
             * To Index
             * @description Position in the returned hit list
             */
            to_index: number;
        };
        /** PurchaseCompleteActionCreate */
        PurchaseCompleteActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: PurchaseCompleteActionCreateType;
            data: components["schemas"]["PurchaseCompleteData"];
        };
        /** PurchaseCompleteData */
        PurchaseCompleteData: {
            /**
             * Sku Ids
             * @description Cart contents (SKU ids) at checkout completion.
             */
            sku_ids: number[];
        };
        /** @example 5eb7cf5a86d9755df3a6c593 */
        PydanticObjectId: string;
        /** SKU */
        SKU: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Category Hierarchy */
            category_hierarchy: string[] | null;
            /** Characteristics */
            characteristics: {
                [key: string]: components["schemas"]["CharacteristicValue"];
            };
        };
        /** SKUDocumentSource */
        SKUDocumentSource: {
            /** Идентификатор Сте */
            "\u0418\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\u0440 \u0421\u0422\u0415": number;
            /** Наименование Сте */
            "\u041D\u0430\u0438\u043C\u0435\u043D\u043E\u0432\u0430\u043D\u0438\u0435 \u0421\u0422\u0415": string;
            /** Категория */
            "\u041A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F": string;
            /** Характеристики Сте */
            "\u0425\u0430\u0440\u0430\u043A\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043A\u0438 \u0421\u0422\u0415": {
                [key: string]: components["schemas"]["CharacteristicValue"];
            };
            /** Category Hierarchy First Level */
            category_hierarchy_first_level?: string;
        };
        /** SearchActionCreate */
        SearchActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: SearchActionCreateType;
            data: components["schemas"]["SearchActionData"];
        };
        /** SearchActionData */
        SearchActionData: {
            /**
             * Query
             * @description Search query text.
             */
            query: string;
            /**
             * Sku Ids
             * @description Top N search result SKU ids in display order (as logged by the client).
             */
            sku_ids: number[];
        };
        /**
         * SearchHit
         * @description Один hit из `hits.hits` ответа search.
         */
        SearchHit: {
            /** Index */
            _index?: string;
            /** Id */
            _id?: string;
            /** Score */
            _score?: number | null;
            _source?: components["schemas"]["SKUDocumentSource"];
            /**
             * Highlight
             * @description "highlight" : {
             *         "Наименование СТЕ.prefix" : [
             *             "<em>Клубника</em> свежая"
             *         ],
             *         "Категория.as_russian_text" : [
             *             "<em>Клубника</em>, земляника"
             *         ]
             *     }
             */
            highlight?: {
                [key: string]: string[];
            };
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Size
             * @default 10
             */
            size: number;
            /**
             * Search For
             * @default Товары
             * @enum {string}
             */
            search_for: SearchRequestSearch_for;
            /**
             * Modes
             * @default lexical+dense
             * @enum {string}
             */
            modes: SearchRequestModes;
            /** Category Hierarchy Filter */
            category_hierarchy_filter?: string[] | null;
            /**
             * Personalized
             * @description When True and the user has an INN set, rerank results using the LightFM model
             * @default false
             */
            personalized: boolean;
        };
        /**
         * SearchResponse
         * @description `total_time` is wall-clock for the handler. `took` is OpenSearch query time in milliseconds.
         */
        SearchResponse: {
            /** Total Time */
            total_time: number;
            /** Took */
            took: number;
            /** Timed Out */
            timed_out: boolean;
            /** Corrected Query */
            corrected_query: string | null;
            /** Skus */
            skus: components["schemas"]["SKU"][];
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /**
             * Personalized
             * @description True when LightFM personalized reranking was applied
             * @default false
             */
            personalized: boolean;
            /** @description When personalized reranking ran: SKUs that moved up vs down vs retrieval order (same retrieve window) */
            personalization_rank_delta?: components["schemas"]["PersonalizationRankDelta"] | null;
        };
        /** SkuBulkByIdsRequest */
        SkuBulkByIdsRequest: {
            /** Ids */
            ids: number[];
        };
        /** SkuCardSessionActionCreate */
        SkuCardSessionActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: SkuCardSessionActionCreateType;
            data: components["schemas"]["SkuCardSessionData"];
        };
        /** SkuCardSessionData */
        SkuCardSessionData: {
            /**
             * Sku Id
             * @description SKU (СТЕ) identifier.
             */
            sku_id: number;
            /**
             * Duration Seconds
             * @description Elapsed time between opening and closing the card, in seconds.
             */
            duration_seconds: number;
            /**
             * Query
             * @description Search query text, if any.
             */
            query?: string | null;
            /**
             * Sku Rank
             * @description Rank of the SKU in the search results, if any.
             */
            sku_rank?: number | null;
        };
        /** SkuIdActionData */
        SkuIdActionData: {
            /**
             * Sku Id
             * @description SKU (СТЕ) identifier.
             */
            sku_id: number;
            /**
             * Query
             * @description Search query text, if any.
             */
            query?: string | null;
            /**
             * Sku Rank
             * @description Rank of the SKU in the search results, if any.
             */
            sku_rank?: number | null;
        };
        /** SkuLikeActionCreate */
        SkuLikeActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: SkuLikeActionCreateType;
            data: components["schemas"]["SkuIdActionData"];
        };
        /** SkuUnlikeActionCreate */
        SkuUnlikeActionCreate: {
            /**
             * Timestamp
             * @description Event time from the client; if omitted, the server sets UTC now. If set, stored unchanged.
             */
            timestamp?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: SkuUnlikeActionCreateType;
            data: components["schemas"]["SkuIdActionData"];
        };
        /** TrainPersonalizationResponse */
        TrainPersonalizationResponse: {
            /** N Users */
            n_users: number;
            /** N Items */
            n_items: number;
            /** N Interactions */
            n_interactions: number;
        };
        /**
         * UserAction
         * @description Append-only log of user actions for personalization (search, SKU card, cart, etc.).
         */
        UserAction: {
            /**
             * Format: objectid
             * @description MongoDB document ObjectID
             * @example 5eb7cf5a86d9755df3a6c593
             */
            id: string;
            user_id: components["schemas"]["PydanticObjectId"];
            type: components["schemas"]["ActionType"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Data */
            data: components["schemas"]["SearchActionData"] | components["schemas"]["SkuCardSessionData"] | components["schemas"]["SkuIdActionData"] | components["schemas"]["PurchaseCompleteData"];
        };
        /** UserMeResponse */
        UserMeResponse: {
            id: components["schemas"]["PydanticObjectId"];
            role: components["schemas"]["UserRole"];
            /** Inn Number */
            inn_number: number | null;
            /** Organization Name */
            organization_name?: string | null;
            /**
             * Okveds
             * @description Distinct OKVED codes from contracts where this INN is customer or supplier; omitted when `inn_number` is unset.
             */
            okveds?: string[] | null;
            /**
             * Actions Count
             * @default 0
             */
            actions_count: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: UserRole;
        /** UserSessionCreate */
        UserSessionCreate: {
            /** Inn Number */
            inn_number?: number | null;
            /** @default default */
            role: components["schemas"]["UserRole"];
        };
        /** UserSessionUpdate */
        UserSessionUpdate: {
            role?: components["schemas"]["UserRole"] | null;
            /** Inn Number */
            inn_number?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCartAddActionCreate = components['schemas']['CartAddActionCreate'];
export type SchemaCartRemoveActionCreate = components['schemas']['CartRemoveActionCreate'];
export type SchemaCharacteristicValue = components['schemas']['CharacteristicValue'];
export type SchemaContract = components['schemas']['Contract'];
export type SchemaContractCreate = components['schemas']['ContractCreate'];
export type SchemaContractListResponse = components['schemas']['ContractListResponse'];
export type SchemaContractUpdate = components['schemas']['ContractUpdate'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaInnSearchResult = components['schemas']['InnSearchResult'];
export type SchemaPersonalizationRankDelta = components['schemas']['PersonalizationRankDelta'];
export type SchemaPersonalizationRankMove = components['schemas']['PersonalizationRankMove'];
export type SchemaPurchaseCompleteActionCreate = components['schemas']['PurchaseCompleteActionCreate'];
export type SchemaPurchaseCompleteData = components['schemas']['PurchaseCompleteData'];
export type SchemaPydanticObjectId = components['schemas']['PydanticObjectId'];
export type SchemaSku = components['schemas']['SKU'];
export type SchemaSkuDocumentSource = components['schemas']['SKUDocumentSource'];
export type SchemaSearchActionCreate = components['schemas']['SearchActionCreate'];
export type SchemaSearchActionData = components['schemas']['SearchActionData'];
export type SchemaSearchHit = components['schemas']['SearchHit'];
export type SchemaSearchRequest = components['schemas']['SearchRequest'];
export type SchemaSearchResponse = components['schemas']['SearchResponse'];
export type SchemaSkuBulkByIdsRequest = components['schemas']['SkuBulkByIdsRequest'];
export type SchemaSkuCardSessionActionCreate = components['schemas']['SkuCardSessionActionCreate'];
export type SchemaSkuCardSessionData = components['schemas']['SkuCardSessionData'];
export type SchemaSkuIdActionData = components['schemas']['SkuIdActionData'];
export type SchemaSkuLikeActionCreate = components['schemas']['SkuLikeActionCreate'];
export type SchemaSkuUnlikeActionCreate = components['schemas']['SkuUnlikeActionCreate'];
export type SchemaTrainPersonalizationResponse = components['schemas']['TrainPersonalizationResponse'];
export type SchemaUserAction = components['schemas']['UserAction'];
export type SchemaUserMeResponse = components['schemas']['UserMeResponse'];
export type SchemaUserSessionCreate = components['schemas']['UserSessionCreate'];
export type SchemaUserSessionUpdate = components['schemas']['UserSessionUpdate'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    post_action_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchActionCreate"] | components["schemas"]["SkuCardSessionActionCreate"] | components["schemas"]["SkuLikeActionCreate"] | components["schemas"]["SkuUnlikeActionCreate"] | components["schemas"]["CartAddActionCreate"] | components["schemas"]["CartRemoveActionCreate"] | components["schemas"]["PurchaseCompleteActionCreate"];
            };
        };
        responses: {
            /** @description Action recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_actions_actions_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All actions for user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAction"][];
                };
            };
        };
    };
    list_contracts_contracts_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contracts (parquet + dynamic), paginated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contract_contracts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description INN not set in session */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contracts_by_inn_contracts_by_inn__inn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contracts where the organization is customer or supplier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contracts_by_sku_id_contracts_by_sku__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contracts that include the given SKU (СТЕ) id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contract_contracts__contract_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Contract is backed by parquet and cannot be removed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contract_contracts__contract_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Contract is backed by parquet and cannot be changed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    search_inn_user_search_inn_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations matching INN prefix or name substring */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InnSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_info_user_set_info_get: {
        parameters: {
            query?: {
                inn_number?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_user_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully logged out (session cleared) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_user_sessions_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                inn_number?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All anonymous session users and their INN bindings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_user_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSessionCreate"];
            };
        };
        responses: {
            /** @description Created session user (new id; use cookie flow separately) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_user_sessions__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_user_sessions__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_session_user_sessions__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["schemas"]["PydanticObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSessionUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_route_images_thumbnail__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_random_skus_dataset_sku_random_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 10 random SKUs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKU"][];
                };
            };
        };
    };
    get_random_contracts_dataset_contract_random_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 10 random contracts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
        };
    };
    get_contracts_by_inn_dataset_contract_by_inn__inn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contracts where the organization is customer or supplier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contracts_by_sku_id_dataset_contract_by_sku__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contracts that include the given SKU (СТЕ) id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sku_dataset_sku__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SKU by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKU"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_skus_by_ids_dataset_sku_bulk_by_ids_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuBulkByIdsRequest"];
            };
        };
        responses: {
            /** @description Map of SKU id to SKU or null if missing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["SKU"] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_dataset_contract__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search for SKUs and contracts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_personalization_search_train_personalization_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Train LightFM personalization model on purchase history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainPersonalizationResponse"];
                };
            };
        };
    };
    clear_search_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clear index */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    index_search_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index SKUs and contracts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_analyzers_search_refresh_analyzers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh search analyzers for the index */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
export enum ActionType {
    search = "search",
    sku_card_session = "sku_card_session",
    sku_like = "sku_like",
    sku_unlike = "sku_unlike",
    cart_add = "cart_add",
    cart_remove = "cart_remove",
    purchase_complete = "purchase_complete"
}
export enum CartAddActionCreateType {
    cart_add = "cart_add"
}
export enum CartRemoveActionCreateType {
    cart_remove = "cart_remove"
}
export enum PurchaseCompleteActionCreateType {
    purchase_complete = "purchase_complete"
}
export enum SearchActionCreateType {
    search = "search"
}
export enum SearchRequestSearch_for {
    "Товары" = "\u0422\u043E\u0432\u0430\u0440\u044B",
    "Услуги" = "\u0423\u0441\u043B\u0443\u0433\u0438"
}
export enum SearchRequestModes {
    lexical = "lexical",
    dense = "dense",
    lexicalPlusdense = "lexical+dense"
}
export enum SkuCardSessionActionCreateType {
    sku_card_session = "sku_card_session"
}
export enum SkuLikeActionCreateType {
    sku_like = "sku_like"
}
export enum SkuUnlikeActionCreateType {
    sku_unlike = "sku_unlike"
}
export enum UserRole {
    default = "default",
    admin = "admin"
}
