/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search/spellcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spellcheck
         * @description Return spellcheck suggestions for a single word.
         */
        post: operations["spellcheck_search_spellcheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Search for products.
         */
        post: operations["search_search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/test-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Search
         * @description Search via Whoogle, then parse products from the top result pages in parallel.
         */
        post: operations["test_search_search_test_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/test-parse-from-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse From Url
         * @description Fetch a page by URL, extract catalog markdown, and parse products.
         */
        post: operations["parse_from_url_search_test_parse_from_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProductTiming */
        ProductTiming: {
            /** Duration Ms */
            duration_ms: number;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
            /** Stages */
            stages?: components["schemas"]["StageTiming"][];
        };
        /** RequestTiming */
        RequestTiming: {
            /** Duration Ms */
            duration_ms: number;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
            /** Stages */
            stages?: components["schemas"]["StageTiming"][];
        };
        /** SearchParams */
        SearchParams: {
            /** Query */
            query: string;
            /** Region */
            region?: string | null;
            /** Source Types */
            source_types?: components["schemas"]["SourceType"][] | null;
            /**
             * Short
             * @default false
             */
            short: boolean;
            /**
             * Spellcheck
             * @default true
             */
            spellcheck: boolean;
        };
        /** SearchResult */
        SearchResult: {
            /** Name */
            name: string;
            /** Characteristics */
            characteristics?: {
                [key: string]: string;
            };
            /** Product Link */
            product_link?: string | null;
            /** Price */
            price?: string | null;
            /** Image Link */
            image_link?: string | null;
            /** Image Links */
            image_links?: string[];
            /** Rating */
            rating?: string | null;
            /** Reviews */
            reviews?: string | null;
            /** Rerank Score */
            rerank_score?: number | null;
            /**
             * Relevant
             * @default true
             */
            relevant?: boolean;
            timing?: components["schemas"]["ProductTiming"] | null;
        };
        /** SearchResults */
        SearchResults: {
            original_params: components["schemas"]["SearchParams"];
            /** Typofix Suggestions */
            typofix_suggestions?: components["schemas"]["TypofixSuggestion"][];
            /** Sources */
            sources: components["schemas"]["SearchSource"][];
            timing?: components["schemas"]["RequestTiming"] | null;
        };
        /** SearchSource */
        SearchSource: {
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url: string;
            /** Source Title */
            source_title: string;
            /** Source Favicon Url */
            source_favicon_url: string | null;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            timing?: components["schemas"]["SourceTiming"] | null;
            /**
             * Results Count
             * @description Number of products found for this source.
             */
            readonly results_count: number;
        };
        /** SourceTiming */
        SourceTiming: {
            /** Duration Ms */
            duration_ms: number;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
            /** Stages */
            stages?: components["schemas"]["StageTiming"][];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: SourceType;
        /**
         * SpellcheckLanguage
         * @enum {string}
         */
        SpellcheckLanguage: SpellcheckLanguage;
        /** SpellcheckRequest */
        SpellcheckRequest: {
            /** Word */
            word: string;
            language: components["schemas"]["SpellcheckLanguage"];
        };
        /** SpellcheckResponse */
        SpellcheckResponse: {
            /** Word */
            word: string;
            language: components["schemas"]["SpellcheckLanguage"];
            /** Suggestions */
            suggestions?: string[];
        };
        /** StageTiming */
        StageTiming: {
            /** Name */
            name: string;
            /** Duration Ms */
            duration_ms: number;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
        };
        /** TypofixSuggestion */
        TypofixSuggestion: {
            source: components["schemas"]["SourceType"];
            /** Suggestion */
            suggestion: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaProductTiming = components['schemas']['ProductTiming'];
export type SchemaRequestTiming = components['schemas']['RequestTiming'];
export type SchemaSearchParams = components['schemas']['SearchParams'];
export type SchemaSearchResult = components['schemas']['SearchResult'];
export type SchemaSearchResults = components['schemas']['SearchResults'];
export type SchemaSearchSource = components['schemas']['SearchSource'];
export type SchemaSourceTiming = components['schemas']['SourceTiming'];
export type SchemaSpellcheckRequest = components['schemas']['SpellcheckRequest'];
export type SchemaSpellcheckResponse = components['schemas']['SpellcheckResponse'];
export type SchemaStageTiming = components['schemas']['StageTiming'];
export type SchemaTypofixSuggestion = components['schemas']['TypofixSuggestion'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    spellcheck_search_spellcheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpellcheckRequest"];
            };
        };
        responses: {
            /** @description Spellcheck suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpellcheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchParams"];
            };
        };
        responses: {
            /** @description Found products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_search_search_test_search_post: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_from_url_search_test_parse_from_url_post: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
export enum SourceType {
    yandex_market = "yandex_market",
    wildberries = "wildberries",
    ozon = "ozon",
    runet = "runet"
}
export enum SpellcheckLanguage {
    ru_RU = "ru-RU",
    en_US = "en-US"
}
